services:
  - type: web
    name: dogs-vs-cats-streamlit
    env: python
    plan: free
    pythonVersion: 3.10.13
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
